OPCUA_SERVER_URL = "opc.tcp://192.168.11.70:4840"

VARIABLES = {
    "rio_comflt": "ns=1;s=R1:AMS_OBI_RIO_ComFlt",
    "hc1_comflt": "ns=1;s=R1:AMS_OBI_HC1_ComFlt",
    "hc2_comflt": "ns=1;s=R1:AMS_OBI_HC2_ComFlt",
    "hc3_comflt": "ns=1;s=R1:AMS_OBI_HC3_ComFlt",
    "hmi_c1_comflt": "ns=1;s=R1:AMS_OBI_HMI_C1_ComFlt",
    "hmi_c2_comflt": "ns=1;s=R1:AMS_OBI_HMI_C2_ComFlt",
    "hmi_c3_comflt": "ns=1;s=R1:AMS_OBI_HMI_C3_ComFlt",
    "evi_p1_comok": "ns=1;s=R1:EVI_P1.OBI.ComOk",
    "evi_p2_comok": "ns=1;s=R1:EVI_P2.OBI.ComOk",
    "evi_p3_comok": "ns=1;s=R1:EVI_P3.OBI.ComOk",
    "evi_p4_comok": "ns=1;s=R1:EVI_P4.OBI.ComOk",
    "evi_p5_comok": "ns=1;s=R1:EVI_P5.OBI.ComOk",
    "evi_p6_comok": "ns=1;s=R1:EVI_P6.OBI.ComOk",
    "ocpp_pdc12_ok": "ns=1;s=R1:EndPointPDC12_B_ConnectOk",
    "ocpp_pdc34_ok": "ns=1;s=R1:EndPointPDC34_B_ConnectOk",
    "ocpp_pdc56_ok": "ns=1;s=R1:EndPointPDC56_B_ConnectOk",
    "bess_comflt": "ns=1;s=R1:ams_obi_jbox_comflt",
    "dcbm1_comflt": "ns=1;s=R1:dcbm1.obi.comflt",
    "dcbm2_comflt": "ns=1;s=R1:dcbm2.obi.comflt",
    "dcbm3_comflt": "ns=1;s=R1:dcbm3.obi.comflt",
    "dcbm4_comflt": "ns=1;s=R1:dcbm4.obi.comflt",
    "dcbm5_comflt": "ns=1;s=R1:dcbm5.obi.comflt",
    "dcbm6_comflt": "ns=1;s=R1:dcbm6.obi.comflt",

    "seq02_branch": "ns=1;s=R1:SEQ02.OLI.Branch_01",
    "seq02_start": "ns=1;s=R1:seq02.ibi.startcmd",
    "seq02_stop": "ns=1;s=R1:seq02.ibi.stopcmd",
    "seq02_ack": "ns=1;s=R1:seq02.ibi.ackcmd",
    "seq02_ic": "ns=1;s=R1:SEQ02.OLI.A.IC1",
    "seq02_pc": "ns=1;s=R1:SEQ02.OLI.A.PC1",
    "seq02_ready": "ns=1;s=R1:seq02.b_ready",
    "seq02_fault": "ns=1;s=R1:SEQ02_OBI_ICPCFlt",
    
    "seq03_branch": "ns=1;s=R1:SEQ03.OLI.Branch_01",
    "seq03_start": "ns=1;s=R1:seq03.ibi.startcmd",
    "seq03_stop": "ns=1;s=R1:seq03.ibi.stopcmd",
    "seq03_ack": "ns=1;s=R1:seq03.ibi.ackcmd",
    "seq03_ic": "ns=1;s=R1:SEQ03.OLI.A.IC2",
    "seq03_pc": "ns=1;s=R1:SEQ03.OLI.A.PC2",
    "seq03_ready": "ns=1;s=R1:seq03.b_ready",
    "seq03_fault": "ns=1;s=R1:SEQ03_OBI_ICPCFlt",
    
    "seq12_ready": "ns=1;s=R1:seq12.b_ready",
    "seq12_fault": "ns=1;s=R1:SEQ12_OBI_ICPCFlt",
    "seq12_ic": "ns=1;s=R1:SEQ12.OLI.A.IC1",
    "seq12_pc": "ns=1;s=R1:SEQ12.OLI.A.PC1",
    "seq12_branch": "ns=1;s=R1:SEQ12.OLI.Branch_01",
    "seq12_ack": "ns=1;s=R1:seq12.ibi.ackcmd",
    
    "hc1p1_current": "ns=1;s=R1:hc1.ori.hb1measi",
    "hc1p1_voltage": "ns=1;s=R1:hc1.ori.hb1measv",
    "pdc1_plim": "ns=1;s=R1:PDCx_R_PLim[1]",
    
    "evi1_cp_status": "ns=1;s=R1:EVI_P1.OLI.CP_StatusCode",
    "evi1_substatus": "ns=1;s=R1:EVI_P1.OLI.CP_SubStatusCode",
    "evi1_error": "ns=1;s=R1:EVI_P1.OLI.CP_ErrorCode",
    "evi1_pilot": "ns=1;s=R1:EVI_P1.OLI.PilotStatusCode",
    "evi1_voltage": "ns=1;s=R1:EVI_P1.OLI.EVSE_MeasVDC",
    "evi1_target_current": "ns=1;s=R1:EVI_P1.OLI.EVSE_OutDCCurrent",
    "evi1_target_voltage": "ns=1;s=R1:EVI_P1.OLI.EVSE_OutDCVoltage",
    "evi1_soc": "ns=1;s=R1:EVI_P1.OLI.SOC",
    "evi1_start": "ns=1;s=R1:B_Start",
    "evi1_stop": "ns=1;s=R1:B_Stop",
    "evi1_ack": "ns=1;s=R1:B_Ack",
    "evi1_es": "ns=1;s=R1:B_ES",
    "evi1_temp1": "ns=1;s=R1:EVI_P1.OLI.Temp1",
    "evi1_temp2": "ns=1;s=R1:EVI_P1.OLI.Temp2",
    "dcbm1_temp_h": "ns=1;s=R1:DCBM1.LiveMesure.TemperatureH",
    "dcbm1_temp_l": "ns=1;s=R1:DCBM1.LiveMesure.TemperatureL",
    
    "seq13_ready": "ns=1;s=R1:seq13.b_ready",
    "seq13_fault": "ns=1;s=R1:SEQ13_OBI_ICPCFlt",
    "seq13_ic": "ns=1;s=R1:SEQ13.OLI.A.IC2",
    "seq13_pc": "ns=1;s=R1:SEQ13.OLI.A.PC2",
    "seq13_branch": "ns=1;s=R1:SEQ13.OLI.Branch_01",
    "seq13_ack": "ns=1;s=R1:seq13.ibi.ackcmd",
    
    "hc2p3_current": "ns=1;s=R1:hc2.ori.hb1measi",
    "hc2p3_voltage": "ns=1;s=R1:hc2.ori.hb1measv",
    "pdc3_plim": "ns=1;s=R1:PDCx_R_PLim[3]",
    
    "evi3_cp_status": "ns=1;s=R1:EVI_P3.OLI.CP_StatusCode",
    "evi3_substatus": "ns=1;s=R1:EVI_P3.OLI.CP_SubStatusCode",
    "evi3_error": "ns=1;s=R1:EVI_P3.OLI.CP_ErrorCode",
    "evi3_pilot": "ns=1;s=R1:EVI_P3.OLI.PilotStatusCode",
    "evi3_voltage": "ns=1;s=R1:EVI_P3.OLI.EVSE_MeasVDC",
    "evi3_target_current": "ns=1;s=R1:EVI_P3.OLI.EVSE_OutDCCurrent",
    "evi3_target_voltage": "ns=1;s=R1:EVI_P3.OLI.EVSE_OutDCVoltage",
    "evi3_soc": "ns=1;s=R1:EVI_P3.OLI.SOC",
    "evi3_start": "ns=1;s=R1:B_Start3",
    "evi3_stop": "ns=1;s=R1:B_Stop3",
    "evi3_ack": "ns=1;s=R1:B_Ack3",
    "evi3_es": "ns=1;s=R1:B_ES3",
    "evi3_temp1": "ns=1;s=R1:EVI_P3.OLI.Temp1",
    "evi3_temp2": "ns=1;s=R1:EVI_P3.OLI.Temp2",
    "dcbm3_temp_h": "ns=1;s=R1:DCBM3.LiveMesure.TemperatureH",
    "dcbm3_temp_l": "ns=1;s=R1:DCBM3.LiveMesure.TemperatureL",
    
    "seq04_branch": "ns=1;s=R1:SEQ04.OLI.Branch_01",
    "seq04_start": "ns=1;s=R1:seq04.ibi.startcmd",
    "seq04_stop": "ns=1;s=R1:seq04.ibi.stopcmd",
    "seq04_ack": "ns=1;s=R1:seq04.ibi.ackcmd",
    "seq04_ic": "ns=1;s=R1:SEQ04.OLI.A.IC3",
    "seq04_pc": "ns=1;s=R1:SEQ04.OLI.A.PC3",
    "seq04_ready": "ns=1;s=R1:seq04.b_ready",
    "seq04_fault": "ns=1;s=R1:SEQ04_OBI_ICPCFlt",
    
    "seq22_ready": "ns=1;s=R1:seq22.b_ready",
    "seq22_fault": "ns=1;s=R1:SEQ22_OBI_ICPCFlt",
    "seq22_ic": "ns=1;s=R1:SEQ22.OLI.A.IC1",
    "seq22_pc": "ns=1;s=R1:SEQ22.OLI.A.PC1",
    "seq22_branch": "ns=1;s=R1:SEQ22.OLI.Branch_01",
    "seq22_ack": "ns=1;s=R1:seq22.ibi.ackcmd",
    
    "hc1p2_current": "ns=1;s=R1:hc1.ori.hb2measi",
    "hc1p2_voltage": "ns=1;s=R1:hc1.ori.hb2measv",
    "pdc2_plim": "ns=1;s=R1:PDCx_R_PLim[2]",
    
    "evi2_cp_status": "ns=1;s=R1:EVI_P2.OLI.CP_StatusCode",
    "evi2_substatus": "ns=1;s=R1:EVI_P2.OLI.CP_SubStatusCode",
    "evi2_error": "ns=1;s=R1:EVI_P2.OLI.CP_ErrorCode",
    "evi2_pilot": "ns=1;s=R1:EVI_P2.OLI.PilotStatusCode",
    "evi2_voltage": "ns=1;s=R1:EVI_P2.OLI.EVSE_MeasVDC",
    "evi2_target_current": "ns=1;s=R1:EVI_P2.OLI.EVSE_OutDCCurrent",
    "evi2_target_voltage": "ns=1;s=R1:EVI_P2.OLI.EVSE_OutDCVoltage",
    "evi2_soc": "ns=1;s=R1:EVI_P2.OLI.SOC",
    "evi2_start": "ns=1;s=R1:B_Start2",
    "evi2_stop": "ns=1;s=R1:B_Stop2",
    "evi2_ack": "ns=1;s=R1:B_Ack2",
    "evi2_es": "ns=1;s=R1:B_ES2",
    "evi2_temp1": "ns=1;s=R1:EVI_P2.OLI.Temp1",
    "evi2_temp2": "ns=1;s=R1:EVI_P2.OLI.Temp2",
    "dcbm2_temp_h": "ns=1;s=R1:DCBM2.LiveMesure.TemperatureH",
    "dcbm2_temp_l": "ns=1;s=R1:DCBM2.LiveMesure.TemperatureL",
    
    "seq23_ready": "ns=1;s=R1:seq23.b_ready",
    "seq23_fault": "ns=1;s=R1:SEQ23_OBI_ICPCFlt",
    "seq23_ic": "ns=1;s=R1:SEQ23.OLI.A.IC2",
    "seq23_pc": "ns=1;s=R1:SEQ23.OLI.A.PC2",
    "seq23_branch": "ns=1;s=R1:SEQ23.OLI.Branch_01",
    "seq23_ack": "ns=1;s=R1:seq23.ibi.ackcmd",
    
    "hc2p4_current": "ns=1;s=R1:hc2.ori.hb2measi",
    "hc2p4_voltage": "ns=1;s=R1:hc2.ori.hb2measv",
    "pdc4_plim": "ns=1;s=R1:PDCx_R_PLim[4]",
    
    "evi4_cp_status": "ns=1;s=R1:EVI_P4.OLI.CP_StatusCode",
    "evi4_substatus": "ns=1;s=R1:EVI_P4.OLI.CP_SubStatusCode",
    "evi4_error": "ns=1;s=R1:EVI_P4.OLI.CP_ErrorCode",
    "evi4_pilot": "ns=1;s=R1:EVI_P4.OLI.PilotStatusCode",
    "evi4_voltage": "ns=1;s=R1:EVI_P4.OLI.EVSE_MeasVDC",
    "evi4_target_current": "ns=1;s=R1:EVI_P4.OLI.EVSE_OutDCCurrent",
    "evi4_target_voltage": "ns=1;s=R1:EVI_P4.OLI.EVSE_OutDCVoltage",
    "evi4_soc": "ns=1;s=R1:EVI_P4.OLI.SOC",
    "evi4_start": "ns=1;s=R1:B_Start4",
    "evi4_stop": "ns=1;s=R1:B_Stop4",
    "evi4_ack": "ns=1;s=R1:B_Ack4",
    "evi4_es": "ns=1;s=R1:B_ES4",
    "evi4_temp1": "ns=1;s=R1:EVI_P4.OLI.Temp1",
    "evi4_temp2": "ns=1;s=R1:EVI_P4.OLI.Temp2",
    "dcbm4_temp_h": "ns=1;s=R1:DCBM4.LiveMesure.TemperatureH",
    "dcbm4_temp_l": "ns=1;s=R1:DCBM4.LiveMesure.TemperatureL",
    
    "seq14_ready": "ns=1;s=R1:seq14.b_ready",
    "seq14_fault": "ns=1;s=R1:SEQ14_OBI_ICPCFlt",
    "seq14_ic": "ns=1;s=R1:SEQ14.OLI.A.IC3",
    "seq14_pc": "ns=1;s=R1:SEQ14.OLI.A.PC3",
    "seq14_branch": "ns=1;s=R1:SEQ14.OLI.Branch_01",
    "seq14_ack": "ns=1;s=R1:seq14.ibi.ackcmd",
    
    "hc3p5_current": "ns=1;s=R1:hc3.ori.hb1measi",
    "hc3p5_voltage": "ns=1;s=R1:hc3.ori.hb1measv",
    "pdc5_plim": "ns=1;s=R1:PDCx_R_PLim[5]",
    
    "evi5_cp_status": "ns=1;s=R1:EVI_P5.OLI.CP_StatusCode",
    "evi5_substatus": "ns=1;s=R1:EVI_P5.OLI.CP_SubStatusCode",
    "evi5_error": "ns=1;s=R1:EVI_P5.OLI.CP_ErrorCode",
    "evi5_pilot": "ns=1;s=R1:EVI_P5.OLI.PilotStatusCode",
    "evi5_voltage": "ns=1;s=R1:EVI_P5.OLI.EVSE_MeasVDC",
    "evi5_target_current": "ns=1;s=R1:EVI_P5.OLI.EVSE_OutDCCurrent",
    "evi5_target_voltage": "ns=1;s=R1:EVI_P5.OLI.EVSE_OutDCVoltage",
    "evi5_soc": "ns=1;s=R1:EVI_P5.OLI.SOC",
    "evi5_start": "ns=1;s=R1:B_Start5",
    "evi5_stop": "ns=1;s=R1:B_Stop5",
    "evi5_ack": "ns=1;s=R1:B_Ack5",
    "evi5_es": "ns=1;s=R1:B_ES5",
    "evi5_temp1": "ns=1;s=R1:EVI_P5.OLI.Temp1",
    "evi5_temp2": "ns=1;s=R1:EVI_P5.OLI.Temp2",
    "dcbm5_temp_h": "ns=1;s=R1:DCBM5.LiveMesure.TemperatureH",
    "dcbm5_temp_l": "ns=1;s=R1:DCBM5.LiveMesure.TemperatureL",
    
    "seq24_ready": "ns=1;s=R1:seq24.b_ready",
    "seq24_fault": "ns=1;s=R1:SEQ24_OBI_ICPCFlt",
    "seq24_ic": "ns=1;s=R1:SEQ24.OLI.A.IC3",
    "seq24_pc": "ns=1;s=R1:SEQ24.OLI.A.PC3",
    "seq24_branch": "ns=1;s=R1:SEQ24.OLI.Branch_01",
    "seq24_ack": "ns=1;s=R1:seq24.ibi.ackcmd",
    
    "hc3p6_current": "ns=1;s=R1:hc3.ori.hb2measi",
    "hc3p6_voltage": "ns=1;s=R1:hc3.ori.hb2measv",
    "pdc6_plim": "ns=1;s=R1:PDCx_R_PLim[6]",
    
    "evi6_cp_status": "ns=1;s=R1:EVI_P6.OLI.CP_StatusCode",
    "evi6_substatus": "ns=1;s=R1:EVI_P6.OLI.CP_SubStatusCode",
    "evi6_error": "ns=1;s=R1:EVI_P6.OLI.CP_ErrorCode",
    "evi6_pilot": "ns=1;s=R1:EVI_P6.OLI.PilotStatusCode",
    "evi6_voltage": "ns=1;s=R1:EVI_P6.OLI.EVSE_MeasVDC",
    "evi6_target_current": "ns=1;s=R1:EVI_P6.OLI.EVSE_OutDCCurrent",
    "evi6_target_voltage": "ns=1;s=R1:EVI_P6.OLI.EVSE_OutDCVoltage",
    "evi6_soc": "ns=1;s=R1:EVI_P6.OLI.SOC",
    "evi6_start": "ns=1;s=R1:B_Start6",
    "evi6_stop": "ns=1;s=R1:B_Stop6",
    "evi6_ack": "ns=1;s=R1:B_Ack6",
    "evi6_es": "ns=1;s=R1:B_ES6",
    "evi6_temp1": "ns=1;s=R1:EVI_P6.OLI.Temp1",
    "evi6_temp2": "ns=1;s=R1:EVI_P6.OLI.Temp2",
    "dcbm6_temp_h": "ns=1;s=R1:DCBM6.LiveMesure.TemperatureH",
    "dcbm6_temp_l": "ns=1;s=R1:DCBM6.LiveMesure.TemperatureL",
}
