OPCUA_SERVER_URL = "opc.tcp://192.168.11.70:4840"

VARIABLES = {
    "rio_comflt": "ns=1;s=R1:AMS_OBI_RIO_ComFlt",
    "hc1_comflt": "ns=1;s=R1:AMS_OBI_HC1_ComFlt",
    "hc2_comflt": "ns=1;s=R1:AMS_OBI_HC2_ComFlt",
    "hc3_comflt": "ns=1;s=R1:AMS_OBI_HC3_ComFlt",
    "hmi_c1_comflt": "ns=1;s=R1:AMS_OBI_HMI_C1_ComFlt",
    "hmi_c2_comflt": "ns=1;s=R1:AMS_OBI_HMI_C2_ComFlt",
    "hmi_c3_comflt": "ns=1;s=R1:AMS_OBI_HMI_C3_ComFlt",
    "evi_p1_comok": "ns=1;s=R1:EVI_P1.OBI.ComOk",
    "evi_p2_comok": "ns=1;s=R1:EVI_P2.OBI.ComOk",
    "evi_p3_comok": "ns=1;s=R1:EVI_P3.OBI.ComOk",
    "evi_p4_comok": "ns=1;s=R1:EVI_P4.OBI.ComOk",
    "evi_p5_comok": "ns=1;s=R1:EVI_P5.OBI.ComOk",
    "evi_p6_comok": "ns=1;s=R1:EVI_P6.OBI.ComOk",
    "ocpp_pdc12_ok": "ns=1;s=R1:EndPointPDC12_B_ConnectOk",
    "ocpp_pdc34_ok": "ns=1;s=R1:EndPointPDC34_B_ConnectOk",
    "ocpp_pdc56_ok": "ns=1;s=R1:EndPointPDC56_B_ConnectOk",
    "bess_comflt": "ns=1;s=R1:ams_obi_jbox_comflt",
    "dcbm1_comflt": "ns=1;s=R1:dcbm1.obi.comflt",
    "dcbm2_comflt": "ns=1;s=R1:dcbm2.obi.comflt",
    "dcbm3_comflt": "ns=1;s=R1:dcbm3.obi.comflt",
    "dcbm4_comflt": "ns=1;s=R1:dcbm4.obi.comflt",
    "dcbm5_comflt": "ns=1;s=R1:dcbm5.obi.comflt",
    "dcbm6_comflt": "ns=1;s=R1:dcbm6.obi.comflt",

    "seq02_branch": "ns=1;s=R1:SEQ02.OLI.Branch_01",
    "seq02_start": "ns=1;s=R1:seq02.ibi.startcmd",
    "seq02_stop": "ns=1;s=R1:seq02.ibi.stopcmd",
    "seq02_ack": "ns=1;s=R1:seq02.ibi.ackcmd",
    "seq02_ic": "ns=1;s=R1:SEQ02.OLI.A.IC1",
    "seq02_pc": "ns=1;s=R1:SEQ02.OLI.A.PC1",
    "seq02_ready": "ns=1;s=R1:seq02.b_ready",
    "seq02_fault": "ns=1;s=R1:SEQ02_OBI_ICPCFlt",
    
    "seq12_ready": "ns=1;s=R1:seq12.b_ready",
    "seq12_fault": "ns=1;s=R1:SEQ12_OBI_ICPCFlt",
    "seq12_ic": "ns=1;s=R1:SEQ12.OLI.A.IC1",
    "seq12_pc": "ns=1;s=R1:SEQ12.OLI.A.PC1",
    "seq12_branch": "ns=1;s=R1:SEQ12.OLI.Branch_01",
    "seq12_ack": "ns=1;s=R1:seq12.ibi.ackcmd",
    
    "hc1p1_current": "ns=1;s=R1:hc1.ori.hb1measi",
    "hc1p1_voltage": "ns=1;s=R1:hc1.ori.hb1measv",
    "pdc1_plim": "ns=1;s=R1:PDCx_R_PLim[1]",
    
    "evi1_cp_status": "ns=1;s=R1:EVI_P1.OLI.CP_StatusCode",
    "evi1_substatus": "ns=1;s=R1:EVI_P1.OLI.CP_SubStatusCode",
    "evi1_error": "ns=1;s=R1:EVI_P1.OLI.CP_ErrorCode",
    "evi1_pilot": "ns=1;s=R1:EVI_P1.OLI.PilotStatusCode",
    "evi1_voltage": "ns=1;s=R1:EVI_P1.OLI.EVSE_MeasVDC",
    "evi1_target_current": "ns=1;s=R1:EVI_P1.OLI.EVSE_OutDCCurrent",
    "evi1_target_voltage": "ns=1;s=R1:EVI_P1.OLI.EVSE_OutDCVoltage",
    "evi1_soc": "ns=1;s=R1:EVI_P1.OLI.SOC",
    "evi1_start": "ns=1;s=R1:B_Start",
    "evi1_stop": "ns=1;s=R1:B_Stop",
    "evi1_ack": "ns=1;s=R1:B_Ack",
    "evi1_es": "ns=1;s=R1:B_ES",
    "evi1_temp1": "ns=1;s=R1:EVI_P1.OLI.Temp1",
    "evi1_temp2": "ns=1;s=R1:EVI_P1.OLI.Temp2",
    "dcbm1_temp_h": "ns=1;s=R1:DCBM1.LiveMesure.TemperatureH",
    "dcbm1_temp_l": "ns=1;s=R1:DCBM1.LiveMesure.TemperatureL",
    
    "seq22_ready": "ns=1;s=R1:seq22.b_ready",
    "seq22_fault": "ns=1;s=R1:SEQ22_OBI_ICPCFlt",
    "seq22_ic": "ns=1;s=R1:SEQ22.OLI.A.IC1",
    "seq22_pc": "ns=1;s=R1:SEQ22.OLI.A.PC1",
    "seq22_branch": "ns=1;s=R1:SEQ22.OLI.Branch_01",
    "seq22_ack": "ns=1;s=R1:seq22.ibi.ackcmd",
    
    "hc1p2_current": "ns=1;s=R1:hc1.ori.hb2measi",
    "hc1p2_voltage": "ns=1;s=R1:hc1.ori.hb2measv",
    "pdc2_plim": "ns=1;s=R1:PDCx_R_PLim[2]",
    
    "evi2_cp_status": "ns=1;s=R1:EVI_P2.OLI.CP_StatusCode",
    "evi2_substatus": "ns=1;s=R1:EVI_P2.OLI.CP_SubStatusCode",
    "evi2_error": "ns=1;s=R1:EVI_P2.OLI.CP_ErrorCode",
    "evi2_pilot": "ns=1;s=R1:EVI_P2.OLI.PilotStatusCode",
    "evi2_voltage": "ns=1;s=R1:EVI_P2.OLI.EVSE_MeasVDC",
    "evi2_target_current": "ns=1;s=R1:EVI_P2.OLI.EVSE_OutDCCurrent",
    "evi2_target_voltage": "ns=1;s=R1:EVI_P2.OLI.EVSE_OutDCVoltage",
    "evi2_soc": "ns=1;s=R1:EVI_P2.OLI.SOC",
    "evi2_start": "ns=1;s=R1:B_Start2",
    "evi2_stop": "ns=1;s=R1:B_Stop2",
    "evi2_ack": "ns=1;s=R1:B_Ack2",
    "evi2_es": "ns=1;s=R1:B_ES2",
    "evi2_temp1": "ns=1;s=R1:EVI_P2.OLI.Temp1",
    "evi2_temp2": "ns=1;s=R1:EVI_P2.OLI.Temp2",
    "dcbm2_temp_h": "ns=1;s=R1:DCBM2.LiveMesure.TemperatureH",
    "dcbm2_temp_l": "ns=1;s=R1:DCBM2.LiveMesure.TemperatureL",
}